name: Test

on:
  push:
    branches: [develop, Voting-develop, Voting-Docker, Voting-Despliegue]
  
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Run migrations
        run: cd decide;python manage.py migrate
      - name: Run tests
        run: cd decide;coverage run --branch --source=. ./manage.py test voting --keepdb; coverage xml;
